services:
  cursor-api:
    image: gtxfury/cursor-2api:v0.1
    container_name: cursor-api
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
